export default function Head() {
  return (
    <>
      <title>HardHart Lottery App</title>
      <meta content="Our smart contract" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  )
}
